config/routes.rb
Rails.application.routes.draw do
  get 'explore/pie'

  resources :todolists
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :todos
  root to: "todos#index"
  get 'todos/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/todolist.rb
class Todolist < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, # :rememberable,
         :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :datasets, inverse_of: :user, dependent: :destroy

  # Omniauth support
def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
     unless user
         user = User.create(
            email: data['email'],
            password: Devise.friendly_token[0,20]
         )
     end
    user
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception, prepend: true
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: [:show, :edit, :update, :destroy]

  # GET /todolists
  # GET /todolists.json
  def index
    @todolists = Todolist.all
  end

  # GET /todolists/1
  # GET /todolists/1.json
  def show
  end

  # GET /todolists/new
  def new
    @todolist = Todolist.new
  end

  # GET /todolists/1/edit
  def edit
  end

  # POST /todolists
  # POST /todolists.json
  def create
    @todolist = Todolist.new(todolist_params)

    respond_to do |format|
      if @todolist.save
        format.html { redirect_to @todolist, notice: 'Todolist was successfully created.' }
        format.json { render :show, status: :created, location: @todolist }
      else
        format.html { render :new }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todolists/1
  # PATCH/PUT /todolists/1.json
  def update
    respond_to do |format|
      if @todolist.update(todolist_params)
        format.html { redirect_to @todolist, notice: 'Todolist was successfully updated.' }
        format.json { render :show, status: :ok, location: @todolist }
      else
        format.html { render :edit }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todolists/1
  # DELETE /todolists/1.json
  def destroy
    @todolist.destroy
    respond_to do |format|
      format.html { redirect_to todolists_url, notice: 'Todolist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todolist
      @todolist = Todolist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todolist_params
      params.require(:todolist).permit(:task, :date, :complete)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:task, :date, :complete)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end	

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/explore_helper.rb
module ExploreHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>tim_todolist</title>
 

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div data-role="page">
	<div data-role="header">Tim</div>
	<div role="main" class="ui-content">
	<%= yield %>
	</div>
	<div data-role="footer">Tim</div>
</div>

</body>
</html>

app/views/todolists/_form.html.erb
<%= form_with(model: todolist, local: true) do |form| %>
  <% if todolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

      <ul>
      <% todolist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task %>
    <%= form.text_field :task, id: :todolist_task %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.number_field :date, id: :todolist_date %>
  </div>

  <div class="field">
    <%= form.label :complete %>
    <%= form.check_box :complete, id: :todolist_complete %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todolists/edit.html.erb
<h1>Editing Todolist</h1>

<%= render 'form', todolist: @todolist %>

<%= link_to 'Show', @todolist %> |
<%= link_to 'Back', todolists_path %>

app/views/todolists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todolists</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Date</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todolists.each do |todolist| %>
      <tr>
        <td><%= todolist.task %></td>
        <td><%= todolist.date %></td>
        <td><%= todolist.complete %></td>
        <td><%= link_to 'Show', todolist %></td>
        <td><%= link_to 'Edit', edit_todolist_path(todolist) %></td>
        <td><%= link_to 'Destroy', todolist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todolist', new_todolist_path %>

app/views/todolists/new.html.erb
<h1>New Todolist</h1>

<%= render 'form', todolist: @todolist %>

<%= link_to 'Back', todolists_path %>

app/views/todolists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @todolist.task %>
</p>

<p>
  <strong>Date:</strong>
  <%= @todolist.date %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @todolist.complete %>
</p>

<%= link_to 'Edit', edit_todolist_path(@todolist) %> |
<%= link_to 'Back', todolists_path %>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task %>
    <%= form.text_field :task, id: :todo_task %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.number_field :date, id: :todo_date %>
  </div>

  <div class="field">
    <%= form.label :complete %>
    <%= form.check_box :complete, id: :todo_complete %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>
<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" href="http://code.jquery.com/mobile/[version]/jquery.mobile-[version].min.css" />
	<script src="http://code.jquery.com/jquery-[version].min.js"></script>
	<script src="http://code.jquery.com/mobile/[version]/jquery.mobile-[version].min.js"></script>
	
<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Date</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr> 
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.task %></td>
        <td><%= todo.date %></td>
        <td><%= todo.complete %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= button_to 'Destroy',  todo,  method: :delete, data: { confirm: 'Are you sure?' } %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

	
<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>


	
<p>
  <strong>Task:</strong>
  <%= @todo.task %>
</p>

<p>
  <strong>Date:</strong>
  <%= @todo.date %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @todo.complete %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>